### ISSUE TITLE
With temperatures, can also we have pump speed?

### ISSUE THREAD

**Issue by Luis-Lourenco** [ChristophFausak/homebridge-resol-vbus#1]
The title sais it all, i already test and have 4 temperatures, its nice to also have pump speed, you think it's easy to get?

thank you.

**Comment by ChristophFausak** [comment]
Yes, this is the planned next step.

Cheers, Christoph

**Comment by ChristophFausak** [comment]
Pump speed is now available. Just update to the latest version.

Cheers, Christoph
